export const getWeatherData = async (city, setWeatherData) => {
    const apiUrl = `https://api.openweathermap.org/data/2.5/weather?q=${city}&units=metric&appid=6b48c660263afbf53c9e3b9297b58b16`;

    try {
        const response = await fetch(apiUrl);
        if (!response.ok) {
            throw new Error(`HTTP error! Status: ${response.status}`);
        }
        const data = await response.json();
        setWeatherData(data);
    } catch (error) {
        console.error('Error fetching weather data:', error);
        setWeatherData(null);
    }
};

export const getCurrentDateTime = () => {
    const currentDate = new Date();
    const options = {
        year: 'numeric',
        month: '2-digit',
        day: '2-digit',
        hour: 'numeric',
        minute: 'numeric',
        hour12: true,
    };
    return currentDate.toLocaleString('en-US', options);
};

export const capitalizeWord = (string) => {
    return string.replace(/\b\w/g, (char) => char.toUpperCase());
  };

  export const countryNameToCode = {
    "Afghanistan": "AF",
    "Albania": "AL",
    "Algeria": "DZ",
    "Andorra": "AD",
    "Angola": "AO",
    "Antigua and Barbuda": "AG",
    "Argentina": "AR",
    "Armenia": "AM",
    "Australia": "AU",
    "Austria": "AT",
    "Azerbaijan": "AZ",
    "Bahamas": "BS",
    "Bahrain": "BH",
    "Bangladesh": "BD",
    "Barbados": "BB",
    "Belarus": "BY",
    "Belgium": "BE",
    "Belize": "BZ",
    "Benin": "BJ",
    "Bhutan": "BT",
    "Bolivia": "BO",
    "Bosnia and Herzegovina": "BA",
    "Botswana": "BW",
    "Brazil": "BR",
    "Brunei": "BN",
    "Bulgaria": "BG",
    "Burkina Faso": "BF",
    "Burundi": "BI",
    "Cabo Verde": "CV",
    "Cambodia": "KH",
    "Cameroon": "CM",
    "Canada": "CA",
    "Central African Republic": "CF",
    "Chad": "TD",
    "Chile": "CL",
    "China": "CN",
    "Colombia": "CO",
    "Comoros": "KM",
    "Congo": "CG",
    "Costa Rica": "CR",
    "Croatia": "HR",
    "Cuba": "CU",
    "Cyprus": "CY",
    "Czechia": "CZ",
    "Denmark": "DK",
    "Djibouti": "DJ",
    "Dominica": "DM",
    "Dominican Republic": "DO",
    "Ecuador": "EC",
    "Egypt": "EG",
    "El Salvador": "SV",
    "Equatorial Guinea": "GQ",
    "Eritrea": "ER",
    "Estonia": "EE",
    "Eswatini": "SZ",
    "Ethiopia": "ET",
    "Fiji": "FJ",
    "Finland": "FI",
    "France": "FR",
    "Gabon": "GA",
    "Gambia": "GM",
    "Georgia": "GE",
    "Germany": "DE",
    "Ghana": "GH",
    "Greece": "GR",
    "Grenada": "GD",
    "Guatemala": "GT",
    "Guinea": "GN",
    "Guinea-Bissau": "GW",
    "Guyana": "GY",
    "Haiti": "HT",
    "Honduras": "HN",
    "Hungary": "HU",
    "Iceland": "IS",
    "India": "IN",
    "Indonesia": "ID",
    "Iran": "IR",
    "Iraq": "IQ",
    "Ireland": "IE",
    "Israel": "IL",
    "Italy": "IT",
    "Jamaica": "JM",
    "Japan": "JP",
    "Jordan": "JO",
    "Kazakhstan": "KZ",
    "Kenya": "KE",
    "Kiribati": "KI",
    "Kuwait": "KW",
    "Kyrgyzstan": "KG",
    "Laos": "LA",
    "Latvia": "LV",
    "Lebanon": "LB",
    "Lesotho": "LS",
    "Liberia": "LR",
    "Libya": "LY",
    "Liechtenstein": "LI",
    "Lithuania": "LT",
    "Luxembourg": "LU",
    "Madagascar": "MG",
    "Malawi": "MW",
    "Malaysia": "MY",
    "Maldives": "MV",
    "Mali": "ML",
    "Malta": "MT",
    "Marshall Islands": "MH",
    "Mauritania": "MR",
    "Mauritius": "MU",
    "Mexico": "MX",
    "Micronesia": "FM",
    "Moldova": "MD",
    "Monaco": "MC",
    "Mongolia": "MN",
    "Montenegro": "ME",
    "Morocco": "MA",
    "Mozambique": "MZ",
    "Myanmar": "MM",
    "Namibia": "NA",
    "Nauru": "NR",
    "Nepal": "NP",
    "Netherlands": "NL",
    "New Zealand": "NZ",
    "Nicaragua": "NI",
    "Niger": "NE",
    "Nigeria": "NG",
    "North Korea": "KP",
    "North Macedonia": "MK",
    "Norway": "NO",
    "Oman": "OM",
    "Pakistan": "PK",
    "Palau": "PW",
    "Palestine State": "PS",
    "Panama": "PA",
    "Papua New Guinea": "PG",
    "Paraguay": "PY",
    "Peru": "PE",
    "Philippines": "PH",
    "Poland": "PL",
    "Portugal": "PT",
    "Qatar": "QA",
    "Romania": "RO",
    "Russia": "RU",
    "Rwanda": "RW",
    "Saint Kitts and Nevis": "KN",
    "Saint Lucia": "LC",
    "Saint Vincent and the Grenadines": "VC",
    "Samoa": "WS",
    "San Marino": "SM",
    "Sao Tome and Principe": "ST",
    "Saudi Arabia": "SA",
    "Senegal": "SN",
    "Serbia": "RS",
    "Seychelles": "SC",
    "Sierra Leone": "SL",
    "Singapore": "SG",
    "Slovakia": "SK",
    "Slovenia": "SI",
    "Solomon Islands": "SB",
    "Somalia": "SO",
    "South Africa": "ZA",
    "South Korea": "KR",
    "South Sudan": "SS",
    "Spain": "ES",
    "Sri Lanka": "LK",
    "Sudan": "SD",
    "Suriname": "SR",
    "Sweden": "SE",
    "Switzerland": "CH",
    "Syria": "SY",
    "Taiwan": "TW",
    "Tajikistan": "TJ",
    "Tanzania": "TZ",
    "Thailand": "TH",
    "Timor-Leste": "TL",
    "Togo": "TG",
    "Tonga": "TO",
    "Trinidad and Tobago": "TT",
    "Tunisia": "TN",
    "Turkey": "TR",
    "Turkmenistan": "TM",
    "Tuvalu": "TV",
    "Uganda": "UG",
    "Ukraine": "UA",
    "United Arab Emirates": "AE",
    "United Kingdom": "GB",
    "United States": "US",
    "Uruguay": "UY",
    "Uzbekistan": "UZ",
    "Vanuatu": "VU",
    "Venezuela": "VE",
    "Vietnam": "VN",
    "Yemen": "YE",
    "Zambia": "ZM",
    "Zimbabwe": "ZW"
  };

  export const cityNameToCountryCode = {
    "Kabul": "AF",
    "Tirana": "AL",
    "Algiers": "DZ",
    "Andorra la Vella": "AD",
    "Luanda": "AO",
    "Buenos Aires": "AR",
    "Yerevan": "AM",
    "Canberra": "AU",
    "Vienna": "AT",
    "Baku": "AZ",
    "Nassau": "BS",
    "Manama": "BH",
    "Dhaka": "BD",
    "Bridgetown": "BB",
    "Minsk": "BY",
    "Brussels": "BE",
    "Belmopan": "BZ",
    "Porto-Novo": "BJ",
    "Thimphu": "BT",
    "Sucre": "BO",
    "Sarajevo": "BA",
    "Gaborone": "BW",
    "Brasilia": "BR",
    "Bandar Seri Begawan": "BN",
    "Sofia": "BG",
    "Ouagadougou": "BF",
    "Gitega": "BI",
    "Praia": "CV",
    "Phnom Penh": "KH",
    "Yaoundé": "CM",
    "Ottawa": "CA",
    "Bangui": "CF",
    "N'Djamena": "TD",
    "Santiago": "CL",
    "Beijing": "CN",
    "Bogotá": "CO",
    "Moroni": "KM",
    "Kinshasa": "CG",
    "San José": "CR",
    "Zagreb": "HR",
    "Havana": "CU",
    "Nicosia": "CY",
    "Prague": "CZ",
    "Copenhagen": "DK",
    "Djibouti": "DJ",
    "Roseau": "DM",
    "Santo Domingo": "DO",
    "Quito": "EC",
    "Cairo": "EG",
    "San Salvador": "SV",
    "Malabo": "GQ",
    "Asmara": "ER",
    "Tallinn": "EE",
    "Mbabane": "SZ",
    "Addis Ababa": "ET",
    "Suva": "FJ",
    "Helsinki": "FI",
    "Paris": "FR",
    "Libreville": "GA",
    "Banjul": "GM",
    "Tbilisi": "GE",
    "Berlin": "DE",
    "Accra": "GH",
    "Athens": "GR",
    "Saint George's": "GD",
    "Guatemala City": "GT",
    "Conakry": "GN",
    "Bissau": "GW",
    "Georgetown": "GY",
    "Port-au-Prince": "HT",
    "Tegucigalpa": "HN",
    "Budapest": "HU",
    "Reykjavik": "IS",
    "New Delhi": "IN",
    "Jakarta": "ID",
    "Tehran": "IR",
    "Baghdad": "IQ",
    "Dublin": "IE",
    "Jerusalem": "IL",
    "Rome": "IT",
    "Kingston": "JM",
    "Tokyo": "JP",
    "Amman": "JO",
    "Nur-Sultan": "KZ",
    "Nairobi": "KE",
    "Tarawa": "KI",
    "Kuwait City": "KW",
    "Bishkek": "KG",
    "Vientiane": "LA",
    "Riga": "LV",
    "Beirut": "LB",
    "Maseru": "LS",
    "Monrovia": "LR",
    "Tripoli": "LY",
    "Vaduz": "LI",
    "Vilnius": "LT",
    "Luxembourg": "LU",
    "Antananarivo": "MG",
    "Lilongwe": "MW",
    "Kuala Lumpur": "MY",
    "Male": "MV",
    "Bamako": "ML",
    "Valletta": "MT",
    "Majuro": "MH",
    "Nouakchott": "MR",
    "Port Louis": "MU",
    "Mexico City": "MX",
    "Palikir": "FM",
    "Chisinau": "MD",
    "Monaco": "MC",
    "Ulaanbaatar": "MN",
    "Podgorica": "ME",
    "Rabat": "MA",
    "Maputo": "MZ",
    "Naypyidaw": "MM",
    "Windhoek": "NA",
    "Yaren": "NR",
    "Kathmandu": "NP",
    "Amsterdam": "NL",
    "Wellington": "NZ",
    "Managua": "NI",
    "Niamey": "NE",
    "Abuja": "NG",
    "Pyongyang": "KP",
    "Skopje": "MK",
    "Oslo": "NO",
    "Muscat": "OM",
    "Islamabad": "PK",
    "Ngerulmud": "PW",
    "East Jerusalem": "PS",
    "Panama City": "PA",
    "Port Moresby": "PG",
    "Asuncion": "PY",
    "Lima": "PE",
    "Manila": "PH",
    "Warsaw": "PL",
    "Lisbon": "PT",
    "Doha": "QA",
    "Bucharest": "RO",
    "Moscow": "RU",
    "Kigali": "RW",
    "Basseterre": "KN",
    "Castries": "LC",
    "Kingstown": "VC",
    "Apia": "WS",
    "San Marino": "SM",
    "Sao Tome": "ST",
    "Riyadh": "SA",
    "Dakar": "SN",
    "Belgrade": "RS",
    "Victoria": "SC",
    "Freetown": "SL",
    "Singapore": "SG",
    "Bratislava": "SK",
    "Ljubljana": "SI",
    "Honiara": "SB",
    "Mogadishu": "SO",
    "Pretoria": "ZA",
    "Seoul": "KR",
    "Juba": "SS",
    "Madrid": "ES",
    "Sri Jayawardenepura Kotte": "LK",
    "Khartoum": "SD",
    "Paramaribo": "SR",
    "Stockholm": "SE",
    "Bern": "CH",
    "Damascus": "SY",
    "Taipei": "TW",
    "Dushanbe": "TJ",
    "Dodoma": "TZ",
    "Bangkok": "TH",
    "Dili": "TL",
    "Lome": "TG",
    "Nuku'alofa": "TO",
    "Port of Spain": "TT",
    "Tunis": "TN",
    "Ankara": "TR",
    "Ashgabat": "TM",
    "Funafuti": "TV",
    "Kampala": "UG",
    "Kyiv": "UA",
    "Abu Dhabi": "AE",
    "London": "GB",
    "Washington, D.C.": "US",
    "Montevideo": "UY",
    "Tashkent": "UZ",
    "Port Vila": "VU",
    "Caracas": "VE",
    "Hanoi": "VN",
    "Sanaa": "YE",
    "Lusaka": "ZM",
    "Harare": "ZW"
  };

  export function getCountryCode(countryOrCityName) {
    return countryNameToCode[countryOrCityName] || cityNameToCountryCode[countryOrCityName] || null;
  }